
use_frameworks!

def socket
  pod 'CocoaAsyncSocket', '~> 7.4.3'
end

target 'Tun2Socks_macOS' do
  platform :osx, '10.11'
  socket
end

target 'Tun2Socks_iOS' do
  platform :ios, '9.0'
  socket
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'YES'
    end
  end
end
